bin/run_app.py
etc/column_mappings.yaml
etc/schema.yaml
reporting_app/__init__.py
reporting_app/templates/datatable.html
reporting_app/templates/datatable.js
reporting_app/templates/proc_report.html
reporting_app/templates/projects.html
reporting_app/templates/run_report.html
reporting_app/templates/runs.html
reporting_app/templates/sample_report.html
rest_api/aggregation/server_side/queries.py

Analysis driver 0.9.2 features

---

etc/column_mappings.yaml
reporting_app/__init__.py
reporting_app/templates/datatable.html
reporting_app/templates/reporting_base.html
rest_api/aggregation/server_side/__init__.py
rest_api/aggregation/server_side/expressions.py
rest_api/aggregation/server_side/queries.py

This contains two branches: 
The bootstrap css navigation bar
The new dot notation in aggregation

Add dot notation

---

etc/column_mappings.yaml
etc/schema.yaml
reporting_app/static/column_formatter.js
reporting_app/templates/datatable.js
reporting_app/templates/proc_report.html
rest_api/aggregation/database_side/queries.py

This PR mostly add new columns and change visibility status

Hide columns

---

reporting_app/__init__.py
reporting_app/static/column_formatter.js
reporting_app/templates/datatable.html
reporting_app/templates/proc_report.html
reporting_app/templates/reporting_base.html
reporting_app/templates/tabbed_datatables.html
reporting_app/util.py
tests/test_reporting_app/test_reporting_app.py

This adds processing/finished/all/etc. views for samples, similar to runs. The configuration of datatables is also simplified.

Pipeline sample runs

---

etc/schema.yaml

add new values for the sample_contamination

add het_hom ratio and ti_tv ratio

---

etc/schema.yaml

added coverage percentile and bases at 5, 15 and 30 X coverage in schema

Coverage percentiles

---

rest_api/limsdb/__init__.py
rest_api/limsdb/queries.py

This should allow us to run test versions of the app without a valid Clarity Postgres connection. Closes #65.

Lazy-loading limsdb

---

config.py
etc/column_mappings.yaml
etc/project_status_definitions.yaml
reporting_app/__init__.py
reporting_app/static/column_formatter.js
reporting_app/templates/datatable.html
reporting_app/templates/datatable.js
reporting_app/templates/reporting_base.html
rest_api/__init__.py
rest_api/aggregation/database_side/queries.py
rest_api/limsdb/__init__.py
rest_api/limsdb/queries/__init__.py
rest_api/limsdb/queries/project_status.py
tests/test_rest_api/test_aggregation/test_database_side.py
tests/test_rest_api/test_aggregation/test_limsdb.py

Add plate table that shows the sample status per plate
Add genotyping and invoicing information to status
Add fix header support and fix the header in project status page
Add class name support for each column provided through the column mapping config file
Add new plate and project status table in project page
Add footer capability to Datable and add one to the project status page
Also add a new page showing the runs created in the last month

Add new columns/table with status info

---

etc/schema.yaml

Adds a projects section in schema and allows for 'project' dataset type in analysis_driver_procs

Project process

---

rest_api/aggregation/database_side/queries.py

Add the expected_yield and expected_coverage to the samples aggregation end point

Expected yield and coverage

---

database_versioning/v0.11_to_v0.11.1.py

Fix get_documents for sample with no data_deleted field

---

etc/column_mappings.yaml
reporting_app/__init__.py
reporting_app/templates/reporting_base.html
rest_api/limsdb/__init__.py
rest_api/limsdb/queries/__init__.py
rest_api/limsdb/queries/run_status.py
rest_api/limsdb/queries/sample_status.py

This adds a page that shows run statuses and samples for sequencing runs started within the last seven days.

#69 run view

---

etc/project_status_definitions.yaml
rest_api/limsdb/queries/__init__.py
rest_api/limsdb/queries/sample_status.py

Following input from @EGCGDanForth, update the step ->  status configuration
also specify no queued process when a `detailed` is true

Fix step to sample status

---

etc/schema.yaml

Required for [pipeline](https://github.com/EdinburghGenomics/Analysis-Driver) stage segmentation.

Adding resume to schema

---

etc/column_mappings.yaml
etc/project_status_definitions.yaml
reporting_app/__init__.py
reporting_app/templates/proc_report.html
rest_api/__init__.py
rest_api/aggregation/database_side/queries.py
rest_api/limsdb/__init__.py
rest_api/limsdb/queries/__init__.py
rest_api/limsdb/queries/run_status.py
rest_api/limsdb/queries/sample_info.py
tests/test_reporting_app/test_reporting_app.py

This PR adds a new lims end point that retrieves sample information (project_id/plate_id/UDFs)
Query that end point to add into the sample reports
Add also pc adapter to run reports

Add columns

---

etc/project_status_definitions.yaml
rest_api/limsdb/queries/sample_status.py

Fix fluid x status

---

etc/column_mappings.yaml
reporting_app/__init__.py
reporting_app/static/datatable.js
reporting_app/static/stylesheets/reporting_app.css
rest_api/aggregation/database_side/queries.py
rest_api/limsdb/__init__.py
tests/js/test_datatable.js

This new PR adds 
- row colouring for filtered run_element/lane/run. 
- new columns showing %Q30 after filtering/trimming.
Also adds ability to not load data from the LIMS database

Color filtered

---

etc/schema.yaml

Add list of source data for each analysis_driver_proc
Add list of file delivered and downloaded to sample

New schema for file deliver

---

etc/schema.yaml
reporting_app/templates/proc_report.html

Adding pipeline/toolset fields as per EdinburghGenomics/Analysis-Driver#270

Pipeline versioning

---

etc/schema.yaml

Add useable reviewer to store the reviewer's name and file size for files delivered and downloaded

new schema fields

---

etc/example_reporting.yaml
rest_api/actions/reviews.py

Fix bug in the run/sample review initiator where the username and password would be set twice

Fix action initiator

---

CHANGELOG.md
etc/column_mappings.yaml
etc/review_thresholds.yaml
reporting_app/static/column_formatter.js
rest_api/aggregation/database_side/__init__.py
tests/js/test_column_formatter.js
tests/test_rest_api/test_aggregation/test_database_side.py

Closes #125 
This PR matches threshold in the reporting app, the automatic review and the SOP.
It also adds the ability to refer to another field when looking for a threshold.

Fix thresholds

---

etc/review_thresholds.yaml
rest_api/actions/automatic_review.py
tests/test_rest_api/test_action/test_automatic_review.py

Mean coverage had wrong name
make sure review comment can be overwritten

Fix automatic sample review

---

rest_api/limsdb/queries/sample_status.py

Fix how the detailed flag is interpreted

---

config.py
etc/project_status_definitions.yaml
rest_api/limsdb/queries/sample_status.py

Add a new list of steps that indicate the start date of a sample

---

etc/project_status_definitions.yaml

Chance Fluidx start date from the time it is transfer to plate to when it actually arrived in the facility

Change fluidx start date

---

reporting_app/__init__.py

Use aggregated sample_ids instead of sample_ids when getting entities for lims_review

lane review bug fix

---

reporting_app/__init__.py
reporting_app/templates/reporting_base.html

add trailing '\' at the end of project status route

---

etc/column_mappings.yaml
etc/schema.yaml
requirements.txt
rest_api/aggregation/database_hooks.py

will fail tests until EGCG-Core v0.8.2 is released

Add support to store number of reads aligning to Phix

---

etc/project_status_definitions.yaml

Add new data release step in Finished def

---

rest_api/actions/automatic_review.py
rest_api/limsdb/queries/__init__.py
tests/test_rest_api/test_action/test_automatic_review.py

 Compare Gb with Gb in sample automatic review

---

etc/column_mappings.yaml

closes #203 
Validation in VB2

Add back the number of samples received 

---

config.py
docker/reporting.yaml
etc/column_mappings.yaml
etc/example_reporting.yaml
etc/schema.yaml
reporting_app/__init__.py
reporting_app/static/column_formatter.js
reporting_app/static/datatable.js
reporting_app/static/stylesheets/reporting_app.css
reporting_app/templates/base.html
reporting_app/util.py
requirements.txt
rest_api/aggregation/database_hooks.py
rest_api/settings.py
tests/js/test_column_formatter.js
tests/js/test_datatable.js
tests/test_reporting_app.py
tests/test_rest_api/test_aggregation/test_database_hooks.py
tests/test_rest_api/test_schema.py

- Closes #184, closes #196
- Updating Eve to 0.8
- Datatables can now display dropdown lists of any type, not just hyperlinks

Reference data storage

---

reporting_app/static/column_formatter.js
tests/js/test_column_formatter.js

This PR fixes the link in project status page single sample do not appear as numbers.
Fixes #206 
This PR only affect the display of a link so it is very low risk.
This will bypass validation

Fix project status link

---

etc/schema.yaml
reporting_app/static/column_formatter.js
tests/js/test_column_formatter.js
tests/test_rest_api/test_schema.py

Adds gc_bias to schema.yaml. Also fixing #208.

GC bias storage, empty list formatting

---

etc/review_thresholds.yaml
rest_api/actions/automatic_review.py
tests/test_rest_api/test_action/test_automatic_review.py

remove automatic review for clean_yield_q30_in_gb that rely on required_yield_q30
closes #215

Remove required_yield_q30

---

etc/column_mappings.yaml

Partial fix for #205 - full fix to be implemented later.

Renaming Gender columns

---

etc/schema.yaml
tests/test_rest_api/test_schema.py

New schema entries for gatk4 pipeline https://github.com/EdinburghGenomics/Analysis-Driver/issues/377
closes #230

Add schema entry required for gatk4 pipelines

---

etc/project_status_definitions.yaml

Filling up new steps introduces recently in the LIMS
closes #238

add manifest parsing step to status definition
